Repository CodeGra-de/CodeGra.de, pull requests merged in 2018-10, with the labels that each got.

#500 Make it possible give grades higher than ten
  migrations/versions/35ca323c91a5_.py
  migrations/versions/42d71a9e58e8_.py
  migrations/versions/5c3b448fc795_.py
  migrations/versions/8693e277a9ac_.py
  psef/lti.py
  psef/models.py
  psef/v1/assignments.py
  psef/v1/submissions.py
  psef_test/test_assignments.py
  psef_test/test_course.py
  psef_test/test_lti.py
  psef_test/test_submissions.py
  seed_data/course_roles.json
  seed_data/permissions.json
  setup.cfg
  src/components/GradeViewer.vue
  src/components/MaximumGrade.vue
  src/components/RubricViewer.vue
  src/components/index.js
  src/constants.js
  src/pages/ManageAssignment.vue
  src/utils.js
  static/lti_canvas_config.xml
  test/unit/specs/MaximumGrade.spec.js
  test/unit/specs/util.spec.js
Labels: LTI, backend, frontend, in progress, mergeable, minor version

#550 Fix broken match files function
  src/components/FileTree.vue
  src/pages/Submission.vue
  test/unit/specs/Submission.spec.js
Labels: in progress, mergeable, patch version

#549 Check if an assignment is loaded before getting its course
  src/components/Sidebar/index.vue
Labels: in progress

#554 Remove the option to automatically generate keys
  config.ini.example
  config.py
  psef/__init__.py
  psef_test/conftest.py
Labels: in progress, minor version

#555 Add student names to plagiarism detail page header
  src/components/PlagiarismDetail.vue
Labels: in progress

#551 Rewrite snippets manager
  .eslintrc.js
  src/components/CodeViewer.vue
  src/components/FeedbackArea.vue
  src/components/Sidebar/UserInfo.vue
  src/components/SnippetManager.vue
  src/components/SubmitButton.vue
  src/store/modules/user.js
  src/store/mutation-types.js
  test/unit/specs/FeedbackArea.spec.js
  test/unit/specs/SnippetManager.spec.js
Labels: in progress

#558 Add meta viewport tag to html head
  index.html
Labels: in progress

#553 Only display users in the course in submission uploader
  migrations/versions/fa7d3baa5778_add_can_list_users_permission.py
  psef/helpers.py
  psef/model_types.py
  psef/models.py
  psef/tasks.py
  psef/v1/assignments.py
  psef/v1/courses.py
  psef/v1/users.py
  psef_test/test_course.py
  psef_test/test_users.py
  seed_data/course_roles.json
  seed_data/permissions.json
  src/components/SubmissionUploader.vue
  src/components/UserSelector.vue
  src/components/UsersManager.vue
  src/pages/ManageAssignment.vue
  src/pages/ManageCourse.vue
  src/pages/Submissions.vue
Labels: backend, frontend, in progress, mergeable

#557 Remove login & register components from sidebar
  src/components/ForgotPassword.vue
  src/components/Login.vue
  src/components/Register.vue
  src/components/Sidebar/Login.vue
  src/components/Sidebar/Register.vue
  src/components/Sidebar/index.vue
  src/components/UserInfo.vue
  src/components/index.js
  src/pages/ForgotPassword.vue
  src/pages/Home.vue
  src/pages/Login.vue
  src/pages/Register.vue
  src/pages/index.js
  src/router/index.js
Labels: discussion needed, in progress, patch version

#563 Only show overview mode when you have permission to see feedback
  src/pages/Submission.vue
Labels: in progress

#546 Add structured logging setup
  .scripts/start_dev.sh
  Makefile
  psef/__init__.py
  psef/blackboard.py
  psef/errors.py
  psef/helpers.py
  psef/linters.py
  psef/lti.py
  psef/mail.py
  psef/models.py
  psef/tasks.py
  psef/v1/assignments.py
  psef/v1/login.py
  psef/v1/lti.py
  psef_test/conftest.py
  requirements.txt
  setup.cfg
Labels: backend, in progress, patch version

#562 Remove unused pip requirements
  requirements.txt
Labels: in progress

#561 Improve handling of LTI
  psef/lti.py
  psef/templates/lti_canvas_config.j2
  psef/v1/lti.py
  psef_test/test_lti.py
  seed_data/lti_canvas_config.xml
  src/pages/LTILaunch.vue
  static/lti_canvas_config.xml
Labels: LTI, in progress, little work, mergeable

#560 Fix submission page layout
  src/components/SubmissionNavBar.vue
  src/pages/Submission.vue
Labels: frontend, in progress, patch version

#508 Add base code and old submissions options to plagiarism runs
  migrations/versions/2952e26424b7_.py
  migrations/versions/30495211ae0c_.py
  migrations/versions/aa2d0a3417a0_.py
  migrations/versions/bec486c454ff_.py
  package.json
  psef/__init__.py
  psef/auth.py
  psef/files.py
  psef/helpers.py
  psef/linters.py
  psef/model_types.py
  psef/models.py
  psef/plagiarism.py
  psef/plagiarism_providers/jplag.py
  psef/tasks.py
  psef/v1/assignments.py
  psef/v1/courses.py
  psef/v1/plagiarism.py
  psef/v1/submissions.py
  psef/v1/users.py
  psef_test/test_assignments.py
  psef_test/test_course.py
  psef_test/test_plagiarism.py
  setup.cfg
  src/components/PlagiarismOverview.vue
  src/components/PlagiarismRunner.vue
  src/pages/ManageAssignment.vue
  test/unit/specs/PlagiarismRunner.spec.js
  test_data/test_old_sumbissions/correct.tar.gz
  test_data/test_old_sumbissions/wrong.tar.gz
Labels: backend, frontend, in progress, mergeable, minor version

#570 Fix canSeeFeedback variable and general feedback line wrapping
  src/components/OverviewMode.vue
  src/pages/Submission.vue
Labels: frontend, in progress, little work

#567 Don't show courses submenu in sidebar when going to / while logged out
  src/components/Sidebar/index.vue
Labels: in progress

#564 Show author of general and line comments
  migrations/versions/d8252005c937_.py
  migrations/versions/e1f30937ba40_.py
  psef/models.py
  psef/v1/submissions.py
  psef_test/test_assignments.py
  psef_test/test_feedback.py
  psef_test/test_submissions.py
  src/components/CodeViewer.vue
  src/components/FeedbackArea.vue
  src/components/OverviewMode.vue
  src/components/SubmissionList.vue
  src/pages/Submission.vue
  src/pages/Submissions.vue
Labels: backend, frontend, in progress, mergeable, patch version

#573 Fix non-editable rubric editor overflow
  src/components/RubricEditor.vue
Labels: frontend, little work, patch version

#556 Fix can_view_plagiarism description
  seed_data/permissions.json
  src/components/DescriptionPopover.vue
  src/components/PermissionsManager.vue
  src/mixins.less
Labels: in progress, patch version

#574 Add manage assignment button to submission list
  src/components/SubmissionList.vue
Labels: in progress

#575 Fix readme
  README.md
Labels: in progress

#568 Make preference manager load value after `show*` prop changes
  src/components/PreferenceManager.vue
  src/pages/Submission.vue
Labels: frontend, in progress

#569 Replace archive dependency with own module
  COPYING
  psef/archive.py
  psef/files.py
  psef/ignore.py
  psef_test/test_assignments.py
  requirements.txt
Labels: backend, in progress, patch version

#566 Reduce the amount of queries and request
  psef/__init__.py
  psef/helpers.py
  psef/lti.py
  psef/models.py
  psef/v1/assignments.py
  psef/v1/courses.py
  psef/v1/submissions.py
  run.py
  src/pages/Submissions.vue
  src/store/modules/courses.js
Labels: backend, enhancement, frontend, in progress, little work

#578 Show plagiarism cases in sidebar
  psef/models.py
  psef_test/test_plagiarism.py
  src/components/LocalHeader.vue
  src/components/PlagiarismDetail.vue
  src/components/PlagiarismOverview.vue
  src/components/Sidebar/PlagiarismCaseList.vue
  src/components/Sidebar/index.vue
  src/components/SubmissionNavBar.vue
  src/pages/LTILaunch.vue
  src/pages/ManageAssignment.vue
  src/pages/Submission.vue
  src/store/index.js
  src/store/modules/plagiarism.js
  src/store/modules/user.js
  src/store/mutation-types.js
  src/utils.js
Labels: in progress

#576 Improve flex old submissions format
  .coveragerc
  COPYING
  psef/files.py
  psef/models.py
  psef/v1/assignments.py
  psef_test/test_plagiarism.py
  test_data/test_old_sumbissions/difficult.tar.gz
  test_data/test_old_sumbissions/wrong.tar.gz
Labels: in progress

#582 Fix old submissions description
  src/components/PlagiarismRunner.vue
Labels: in progress

#580 Add key prop to transition component in sidebar
  src/components/Sidebar/index.vue
Labels: in progress

#584 Remove animations from login and register buttons
  src/components/Sidebar/index.vue
Labels: in progress

#579 Ensure all rubric rows have a maximum amount of >= 0 points
  psef/helpers.py
  psef/models.py
  psef/v1/assignments.py
  psef_test/test_assignments.py
  psef_test/test_submissions.py
Labels: backend, in progress, minor version

#592 Make it possible to select a dedicated temporary directory
  config.ini.example
  config.py
  psef/files.py
  psef/v1/assignments.py
Labels: backend, enhancement, in progress, patch version

#595 Redesign submission download dropdown
  src/mixins.less
  src/pages/Submission.vue
Labels: in progress

#591 Make sure codeviewer is full width on medium pages
  src/components/LocalHeader.vue
  src/pages/Submission.vue
  static/img/bars.svg
Labels: frontend, in progress, patch version

#587 Move revision selector to filetree
  src/components/FileTree.vue
  src/components/PreferenceManager.vue
  src/pages/Submission.vue
Labels: in progress

#598 Fix back button border radius on non-small screens
  src/components/LocalHeader.vue
Labels: in progress

#589 Only submit rubric items or normal grade
  src/components/GradeViewer.vue
Labels: bug, frontend, in progress, patch version

#602 Fix revision selector issues
  src/components/FileTree.vue
Labels: in progress

#571 Start using enum to store permissions in the backend
  .coveragerc
  .scripts/create_permission.py
  .scripts/generate_permissions_py.py
  .travis.yml
  Makefile
  README.md
  docs/psef_api/psef.rst
  manage.py
  psef/__init__.py
  psef/auth.py
  psef/cache.py
  psef/errors.py
  psef/exceptions.py
  psef/helpers.py
  psef/model_types.py
  psef/models.py
  psef/parsers.py
  psef/permissions.py
  psef/plagiarism_providers/jplag.py
  psef/v1/assignments.py
  psef/v1/code.py
  psef/v1/courses.py
  psef/v1/linters.py
  psef/v1/login.py
  psef/v1/lti.py
  psef/v1/permissions.py
  psef/v1/plagiarism.py
  psef/v1/roles.py
  psef/v1/snippets.py
  psef/v1/submissions.py
  psef/v1/users.py
  psef_test/conftest.py
  psef_test/test_assignments.py
  psef_test/test_code.py
  psef_test/test_course.py
  psef_test/test_login.py
  psef_test/test_permissions.py
  psef_test/test_plagiarism.py
Labels: in progress

#596 Justify description popover text
  index.html
  seed_data/permissions.json
  src/components/DescriptionPopover.vue
  src/components/PermissionsManager.vue
Labels: in progress

#590 Show manage assignment button based on permissions
  src/components/SubmissionList.vue
Labels: frontend, in progress, patch version

#588 Refactor lti passback code
  Makefile
  psef/__init__.py
  psef/exceptions.py
  psef/linters.py
  psef/lti.py
  psef/models.py
  psef/tasks.py
  psef/v1/assignments.py
  psef/v1/lti.py
  psef_test/test_lti.py
  psef_test/test_permissions.py
  requirements.txt
  test_data/example_strings/invalid_replace_result.xml
  test_data/example_strings/invalid_xml.xml
  test_data/example_strings/valid_replace_result.xml
Labels: LTI, backend, in progress

#599 Improve revised file popovers
  src/components/FileTree.vue
  src/pages/Submission.vue
Labels: in progress

#600 Add submissions to the sidebar
  manage.py
  psef/v1/assignments.py
  psef_test/test_assignments.py
  src/components/CodeViewer.vue
  src/components/DivideSubmissions.vue
  src/components/GeneralFeedbackArea.vue
  src/components/GradeViewer.vue
  src/components/LocalHeader.vue
  src/components/PdfViewer.vue
  src/components/RubricEditor.vue
  src/components/Sidebar/AssignmentListItem.vue
  src/components/Sidebar/SubmissionsSidebarList.vue
  src/components/Sidebar/index.vue
  src/components/SubmissionList.vue
  src/components/SubmissionNavBar.vue
  src/components/SubmissionUploader.vue
  src/components/SubmitButton.vue
  src/pages/ManageAssignment.vue
  src/pages/Submission.vue
  src/pages/Submissions.vue
  src/store/modules/courses.js
  src/store/modules/plagiarism.js
  src/store/mutation-types.js
  src/utils/FilterSubmissionsManager.js
  src/utils/index.js
  test/unit/specs/Submission.spec.js
  test/unit/specs/courses.spec.js
  test/unit/specs/util.spec.js
Labels: frontend, in progress

#609 Remove disabled tab logic in FileTree
  src/components/FileTree.vue
Labels: in progress

#605 Fix display of inline feedback authors
  src/components/FeedbackArea.vue
Labels: frontend, in progress, mergeable, patch version

#607 Show toast when localstorage doesn't work
  src/main.js
  src/pages/LTILaunch.vue
  src/store/index.js
Labels: frontend, in progress, little work

#606 Fix margins in local header
  src/components/LocalHeader.vue
  src/components/SubmissionList.vue
  src/pages/ManageCourse.vue
  src/pages/Submission.vue
Labels: frontend, in progress, little work

#612 Fix duplicate keys for deleted files in OverviewMode
  src/components/OverviewMode.vue
Labels: frontend, in progress, little work, patch version

#613 Add <noscript> tag
  index.html
Labels: in progress

#615 Fix LocalHeader margin
  src/components/LocalHeader.vue
Labels: in progress

#617 Make sure username doesn't overflow
  src/components/Sidebar/index.vue
Labels: bug, frontend, in progress, patch version

#618 Make sure it is possible to do a `HEAD` request on the files route
  psef/v1/files.py
  psef_test/test_files.py
Labels: backend, in progress, patch version

#623 Improve speed of file tree operations
  psef/files.py
  psef/models.py
  src/components/FileTree.vue
Labels: backend, in progress, patch version, performance

#616 Fix flickering popovers in the HomeGrid
  src/components/AssignmentState.vue
  src/components/HomeGrid.vue
Labels: in progress

#622 Make it impossible to submit empty archives
  psef/files.py
  psef_test/test_assignments.py
  test_data/test_submissions/empty_submission.tar.gz
Labels: backend, in progress, patch version

#625 Fix grade history popover boundary
  src/pages/Submission.vue
Labels: in progress

#627 Replace submitted symlinks with actual files
  psef/archive.py
  psef/errors.py
  psef/exceptions.py
  psef/files.py
  psef/helpers.py
  psef/v1/assignments.py
  psef_test/test_about.py
  psef_test/test_assignments.py
  psef_test/test_code.py
  src/components/FileUploader.vue
  src/components/SubmitButton.vue
Labels: in progress

#629 Request time should be a float
  psef/__init__.py
Labels: backend

#632 Revert itsdangerous update
  requirements.txt
Labels: in progress

#631 Remove celery from health route
  psef/v1/about.py
  psef_test/test_about.py
Labels: backend, in progress, patch version

#633 Fix fontSize & contextAmount on submission page
  src/pages/Submission.vue
Labels: in progress

#630 Make sure redirect works when deleting files with cgignore
  src/components/SubmissionUploader.vue
Labels: bug, frontend, in progress, patch version

#634 Fix off by one error in plagiarism export
  src/components/PlagiarismDetail.vue
Labels: bug, frontend, patch version

#635 Close the CGIgnore modal after submission
  src/components/SubmissionUploader.vue
Labels: in progress

#636 Check if submissions are loaded before mutating them
  src/store/modules/courses.js
  test/unit/specs/courses.spec.js
Labels: in progress

#638 When adding a rubric sometimes double rows would show up
  psef/models.py
  psef/v1/assignments.py
  src/components/SubmitButton.vue
Labels: backend, bug, in progress

#643 Reload submissions after rubric changed
  src/components/RubricEditor.vue
Labels: in progress

#645 Fix order of exported plagiarism matches
  src/components/PlagiarismDetail.vue
Labels: in progress

#644 Check can_assign_graders permission in submissions list
  src/components/SubmissionList.vue
  src/pages/Submissions.vue
Labels: in progress

#637 Fallback for position: sticky on the sidebar
  src/App.vue
  src/components/FileTree.vue
  src/components/LocalHeader.vue
  src/components/PlagiarismDetail.vue
  src/components/Sidebar/index.vue
  src/main.js
Labels: in progress

#648 Make it impossible to select multiple items from the same rubric row
  psef/models.py
  psef/v1/submissions.py
  psef_test/test_submissions.py
Labels: backend, bug, in progress, patch version

#649 Fix IE11 compatibality
  src/polyfills.js
Labels: in progress

#652 Fix text overflow in plagiarism export modal
  src/components/PlagiarismDetail.vue
Labels: in progress

#524 Documentation
  .scripts/generate_permissions_py.py
  docs/_static/_images/assignment_details.png
  docs/_static/_images/assignment_state.png
  docs/_static/_images/assignments.png
  docs/_static/_images/assignments_filter_TA.png
  docs/_static/_images/assignments_filter_student.png
  docs/_static/_images/code_viewer.png
  docs/_static/_images/course_TA.png
  docs/_static/_images/courses.png
  docs/_static/_images/courses_TA.png
  docs/_static/_images/linter.ogv
  docs/_static/_images/linters.webm
  docs/_static/_images/logo.svg
  docs/_static/_images/pdf_viewer.png
  docs/_static/_images/snippet.webm
  docs/_static/_images/submissions_student.png
  docs/_static/_images/user_info.png
  docs/_static/style.css
  docs/about/authors.rst
  docs/about/changelog.rst
  docs/about/codegradefeatures.rst
  docs/about/contact.rst
  docs/about/contributing.rst
  docs/about/history.rst
  docs/about/technologies.rst
  docs/about/whatis.rst
  docs/api.rst
  docs/building.rst
  docs/code.rst
  docs/conf.py
  docs/course_permissions.csv
  docs/global_permissions.csv
  docs/index.rst
  docs/manual.rst
  docs/psef_api/modules.rst
  docs/psef_api/psef.plagiarism_providers.rst
  docs/psef_api/psef.rst
  docs/psef_api/psef.v1.rst
  docs/running.rst
  docs/user/codeviewer.rst
  docs/user/lms.rst
  docs/user/management.rst
  docs/user/overview.rst
  docs/user/permissions.rst
  docs/user/plagiarism.rst
  docs/user/preferences.rst
  docs/user/quickstart.rst
  psef/permissions.py
  requirements.txt
Labels: in progress
