Repository CodeGra-de/CodeGra.de, pull requests merged in 2018-09, with the labels that each got.

#477 Fix infinite loop overview mode
  src/components/OverviewMode.vue
  src/pages/Submission.vue
Labels: frontend, in progress, patch version, priority-0-high

#489 Fix sidebar course management button in assignment list
  src/components/Sidebar/CourseListItem.vue
  src/components/Sidebar/index.vue
Labels: in progress, patch version

#480 Change homepage to login screen
  .eslintrc.js
  src/components/AssignmentState.vue
  src/components/HomeGrid.vue
  src/components/Sidebar/index.vue
  src/components/index.js
  src/pages/Home.vue
  src/utils.js
  static/img/feature-1.png
  static/img/feature-2.png
  static/img/feature-3.png
  static/img/screenshot.png
Labels: frontend, in progress, patch version

#490 Fix minimum duration of loader for role dropdown
  src/components/UsersManager.vue
Labels: frontend, in progress, patch version

#492 Allow .tar.xz archives to be uploaded
  psef/files.py
  psef_test/test_assignments.py
  test_data/test_submissions/single_file_archive.tar.xz
Labels: in progress

#496 Add logo to header on homepage
  src/components/HomeGrid.vue
Labels: in progress

#495 Change background color of inline feedback
  src/components/FeedbackArea.vue
Labels: in progress

#501 Use a masonry layout on home page
  npm-shrinkwrap.json
  package.json
  src/components/HomeGrid.vue
  src/main.js
  src/pages/Home.vue
Labels: frontend, in progress, patch version

#486 Plagiarism checkers
  .travis.yml
  config.ini.example
  config.py
  docs/psef_api/modules.rst
  docs/psef_api/psef.plagiarism_providers.rst
  docs/psef_api/psef.rst
  migrations/versions/19f00a8b1316_.py
  migrations/versions/5c3b448fc795_.py
  psef/__init__.py
  psef/auth.py
  psef/files.py
  psef/helpers.py
  psef/json_encoders.py
  psef/linters.py
  psef/models.py
  psef/plagiarism.py
  psef/plagiarism_providers/__init__.py
  psef/plagiarism_providers/jplag.py
  psef/tasks.py
  psef/v1/__init__.py
  psef/v1/assignments.py
  psef/v1/plagiarism.py
  psef_test/conftest.py
  psef_test/test_plagiarism.py
  requirements.txt
  seed_data/course_roles.json
  seed_data/permissions.json
  setup.cfg
  src/App.vue
  src/components/CGIgnoreFile.vue
  src/components/DivideSubmissions.vue
  src/components/FeedbackArea.vue
  src/components/LocalHeader.vue
  src/components/Notifications.vue
  src/components/PlagiarismDetail.vue
  src/components/PlagiarismOverview.vue
  src/components/PlagiarismRunner.vue
  src/components/PreferenceManager.vue
  src/components/RubricEditor.vue
  src/components/Sidebar/index.vue
  src/components/SubmissionList.vue
  src/components/SubmitButton.vue
  src/components/UserSelector.vue
  src/components/UsersManager.vue
  src/components/index.js
  src/constants.js
  src/mixins.less
  src/pages/ManageAssignment.vue
  src/pages/Submissions.vue
  src/router/index.js
  src/style.less
Labels: backend, frontend, in progress, minor version

#513 Add placeholders to plagiarism options
  psef/plagiarism.py
  psef/plagiarism_providers/jplag.py
  psef_test/test_plagiarism.py
  src/components/PlagiarismRunner.vue
Labels: backend, frontend, in progress, little work, patch version

#519 Fix incorrect rubric not saved message with incremental submission
  src/components/GradeViewer.vue
Labels: frontend, in progress, little work, mergeable, patch version

#521 Add a minimum duration on the permission manager loaders
  src/components/PermissionsManager.vue
Labels: frontend, in progress, little work, patch version

#534 Fix forgot password link in password help popup
  src/components/Login.vue
  src/components/UserInfo.vue
  src/pages/Home.vue
Labels: frontend, in progress, little work, patch version

#533 Fix error message when logging in
  psef/v1/login.py
Labels: backend, in progress, little work

#535 Throw an API error when a rubric row contains an empty header
  psef/v1/assignments.py
  psef_test/test_assignments.py
Labels: backend, in progress, little work, minor version

#528 Fix broken matchFiles function
  .babelrc
  .codeclimate.yml
  .gitignore
  .travis.yml
  .travis/run
  npm-shrinkwrap.json
  package.json
  src/components/CodeViewer.vue
  src/components/DiffViewer.vue
  src/components/OverviewMode.vue
  src/main.js
  src/pages/Submission.vue
  test/e2e/specs/test.js
  test/unit/.eslintrc
  test/unit/setup.js
  test/unit/specs/Hello.spec.js
  test/unit/specs/Submission.spec.js
Labels: in progress

#538 Increase testing speed by reducing duplicate cases
  .travis.yml
  .travis/run
  Makefile
  psef/__init__.py
  psef_test/test_feedback.py
  psef_test/test_linting.py
  psef_test/test_plagiarism.py
Labels: in progress

#547 Disable non blocking IO for travis
  .travis.yml
Labels: in progress

#536 Make it possible to delete submission that have plagiarism cases
  migrations/versions/77d138b081a4_.py
  psef/models.py
  psef/v1/code.py
  psef_test/test_code.py
  psef_test/test_submissions.py
Labels: backend, in progress, patch version

#529 Improve speed of diffing by using another library
  npm-shrinkwrap.json
  package.json
  src/components/DiffViewer.vue
  test/unit/.eslintrc
  test/unit/setup.js
  test/unit/specs/DiffViewer.spec.js
Labels: in progress
