Repository CodeGra-de/CodeGra.de, pull requests merged in 2018-11, with the labels that each got.

#662 Add support for more encodings
  src/components/CodeViewer.vue
  src/components/OverviewMode.vue
  src/utils/decode.js
Labels: frontend, in progress, patch version

#663 Revert "Add support for more encodings"
  src/components/CodeViewer.vue
  src/components/OverviewMode.vue
  src/utils/decode.js
Labels: in progress

#664 Prevent clicks on DescriptionPopover from bubbeling up
  src/components/DescriptionPopover.vue
Labels: in progress

#666 Support latin1 encoding
  src/components/CodeViewer.vue
  src/components/DiffViewer.vue
  src/components/OverviewMode.vue
  src/components/PlagiarismDetail.vue
  src/utils/decode.js
  test/unit/specs/decode.spec.js
  test/unit/test_data/binary
  test/unit/test_data/latin1.txt
  test/unit/test_data/utf8.txt
Labels: in progress

#672 Remove SubmitButton docs
  src/components/SubmitButton.vue
Labels: in progress

#668 Minimum duration for saving snippets
  src/components/FeedbackArea.vue
  src/components/SnippetManager.vue
Labels: in progress

#671 Add space between linter feedback columns
  src/components/LinterFeedbackArea.vue
Labels: in progress

#673 Make it impossible to override the special files of the fs
  psef/exceptions.py
  psef/files.py
  psef/models.py
  psef/v1/submissions.py
  psef_test/test_assignments.py
  psef_test/test_submissions.py
  test_data/test_submissions/rename_file_archive.tar.gz
Labels: in progress

#680 Update changelog
  docs/about/changelog.rst
Labels: in progress

#686 Rename CodeGra.de to CodeGrade everywhere
  config.py
  docs/about/contact.rst
  docs/building.rst
  docs/running.rst
  index.html
  psef/errors.py
  src/App.vue
  src/components/FooterBar.vue
  src/components/UserInfo.vue
  src/pages/Submissions.vue
  src/pages/title.js
Labels: in progress

#687 Fix docs formatting
  docs/about/changelog.rst
  docs/about/contact.rst
  docs/building.rst
  docs/conf.py
  docs/index.rst
  docs/running.rst
  docs/user/codeviewer.rst
  docs/user/lms.rst
  docs/user/management.rst
  docs/user/overview.rst
  docs/user/permissions.rst
  docs/user/plagiarism.rst
  docs/user/preferences.rst
  docs/user/quickstart.rst
  requirements.txt
Labels: in progress

#690 Fix plagiarism detail viewer
  src/components/PlagiarismDetail.vue
Labels: in progress

#682 Update course and assignment name on LTI launch
  psef/lti.py
  psef_test/test_lti.py
Labels: LTI, backend, in progress

#681 Do lti launch on grade result
  psef/auth.py
  psef/lti.py
  psef/models.py
  psef/v1/lti.py
  src/pages/LTILaunch.vue
Labels: LTI, backend, frontend, in progress

#683 Feature/min password strength
  config.ini.example
  config.py
  psef/exceptions.py
  psef/helpers/__init__.py
  psef/helpers/validate.py
  psef/v1/login.py
  psef/v1/users.py
  psef_test/test_login.py
  psef_test/test_users.py
  requirements.txt
  src/components/Register.vue
  src/components/SubmitButton.vue
  src/components/UserInfo.vue
  src/pages/ResetPassword.vue
Labels: in progress

#692 Always do an initial grade passback
  psef/lti.py
  psef/models.py
  psef/tasks.py
  psef/v1/assignments.py
  psef_test/test_lti.py
Labels: LTI, backend, in progress

#693 Various small logging fixes
  psef/__init__.py
  psef/helpers/__init__.py
Labels: in progress

#694 Improve speed of plagiarism route
  migrations/versions/bcaac30cfecf_.py
  psef/model_types.py
  psef/models.py
  psef/v1/assignments.py
  psef/v1/plagiarism.py
  psef_test/test_submissions.py
  src/store/modules/plagiarism.js
Labels: in progress

#697 Enhancement/check password strength on login
  psef/exceptions.py
  psef/helpers/validate.py
  psef/v1/login.py
  psef_test/test_login.py
  src/components/Login.vue
  src/store/modules/user.js
Labels: in progress

#702 Show holiday logo for specific date ranges
  src/components/Sidebar/index.vue
  static/img/CodeGrade_christmas.svg
  static/img/CodeGrade_christmas_dark.svg
Labels: in progress

#701 Fix plagiarism options popover styling
  src/components/PlagiarismRunner.vue
Labels: in progress

#700 Add loader to plagiarism runs that are still running
  src/components/PlagiarismRunner.vue
Labels: blocked, in progress

#704 Update changelog for release HereBeMonsters.2
  docs/about/changelog.rst
Labels: in progress
