Repository CodeGra-de/CodeGra.de, pull requests merged in 2018-04, with the labels that each got.

#413 Move shared code between `CourseRole` and `Role` to an abstract class
  .coveragerc
  psef/models.py
Labels: backend, in progress, no version, technical debt

#415 Fix frontend issues
  src/components/LocalHeader.vue
  src/components/SubmissionList.vue
Labels: frontend, in progress, patch version, priority-0-high

#416 Make sure docs are published at docs.codegra.de
  .travis.yml
Labels: backend, in progress, no version

#419 Fix ignore file error
  src/components/FileUploader.vue
  src/components/SubmissionUploader.vue
  src/components/SubmitButton.vue
Labels: in progress

#425 Fix default value of function for `beforeUpload`
  src/components/FileUploader.vue
Labels: frontend, in progress, mergeable, patch version

#420 Make sure latest filter is applied before assigned to me filter
  src/utils.js
Labels: bug, frontend, in progress, patch version

#428 Make sure linter remove button displays state
  src/components/Linter.vue
Labels: frontend, in progress, mergeable, patch version

#429 Make sure 'can_edit_others_work' permission is not deleted on migration
  migrations/versions/729a1509580b_.py
Labels: in progress

#430 Fix reminder times
  src/components/Notifications.vue
  src/store/modules/courses.js
Labels: in progress

#431 Actually make sure permissions are not deleted in migration
  migrations/versions/729a1509580b_.py
Labels: in progress

#432 Make sure data is reloaded when switching course
  src/components/PermissionsManager.vue
  src/components/UsersManager.vue
  src/pages/ManageCourse.vue
Labels: Release bug, frontend, in progress, mergeable

#438 Store submissions filter on any keyup, not just enter
  src/components/SubmissionList.vue
Labels: in progress, patch version

#434 Fix points width in non-editable rubric editor
  src/components/RubricEditor.vue
Labels: in progress, patch version

#439 Fix tab borders in the dark theme
  src/components/RubricViewer.vue
  src/mixins.less
Labels: in progress, patch version

#441 Use placeholder for the "new category" field in the rubric editor
  src/components/RubricEditor.vue
  src/components/RubricViewer.vue
Labels: in progress, patch version

#446 Make sure general comment is updated after switching submission
  src/components/FileUploader.vue
  src/components/GeneralFeedbackArea.vue
  src/pages/Submission.vue
Labels: frontend, in progress, mergeable, patch version

#447 Release stable 'GotfriedMetDenBaard.1'
  migrations/versions/729a1509580b_.py
  src/components/FileUploader.vue
  src/components/GeneralFeedbackArea.vue
  src/components/PermissionsManager.vue
  src/components/RubricEditor.vue
  src/components/RubricViewer.vue
  src/components/SubmissionList.vue
  src/components/UsersManager.vue
  src/mixins.less
  src/pages/ManageCourse.vue
  src/pages/Submission.vue
Labels: in progress
