Repository CodeGra-de/CodeGra.de, pull requests merged in 2018-05, with the labels that each got.

#451 Make sure non top-level submenus are hidden
  src/components/Sidebar/index.vue
Labels: frontend, in progress, mergeable, olmo <strike>bug</strike> feature, patch version

#452 Fix non-editable general feedback area
  src/components/GeneralFeedbackArea.vue
Labels: in progress, mergeable

#455 Only force overview mode when not set in query parameters
  src/pages/Submission.vue
Labels: frontend, mergeable, patch version

#450 Make sure grade is updated when non incremental rubric is submitted
  src/components/GradeViewer.vue
  src/components/RubricViewer.vue
Labels: frontend, in progress, mergeable, patch version

#456 Fix sidebar shadow with more than one submenu level
  src/components/Sidebar/index.vue
Labels: in progress

#457 Make long rubric item headers show an ellipsis
  src/components/GradeViewer.vue
  src/components/RubricViewer.vue
Labels: bug, frontend, in progress, patch version

#458 Release stable 'GodfriedMetDenBaard.2'
  psef/models.py
  psef/v1/assignments.py
  psef_test/test_assignments.py
  requirements.txt
  src/components/GeneralFeedbackArea.vue
  src/components/GradeViewer.vue
  src/components/RubricViewer.vue
  src/components/Sidebar/index.vue
  src/pages/Submission.vue
Labels: in progress
