Repository CodeGra-de/CodeGra.de, pull requests merged in 2019-02, with the labels that each got.

#748 Make sure submit buttons work correctly when submitFunction is used
  src/components/Linter.vue
  src/components/Register.vue
  src/components/SubmitButton.vue
  src/components/UserInfo.vue
  src/pages/ResetPassword.vue
Labels: in progress

#751 Show message when no groups exist
  src/components/GroupsManagement.vue
Labels: in progress

#750 Make assignment group set row clickable
  src/components/AssignmentGroup.vue
Labels: in progress

#756 Make sure author of feedback is shown
  src/components/FeedbackArea.vue
  src/components/FloatingFeedbackButton.vue
  src/components/InnerCodeViewer.vue
Labels: in progress

#758 Smaller group set management buttons
  src/components/GroupSetManager.vue
Labels: in progress

#752 Make the user selector more clear
  npm-shrinkwrap.json
  package.json
  src/components/GroupManagement.vue
  src/components/UserSelector.vue
Labels: in progress

#757 Fix group set to assignment after submissions
  psef/models/assignment.py
  psef/models/group.py
  psef/models/user.py
  psef/v1/assignments.py
  psef_test/test_groups.py
Labels: in progress

#753 Add group set management buttons
  src/components/AssignmentGroup.vue
  src/components/GroupManagement.vue
  src/mixins.less
  src/pages/ManageAssignment.vue
Labels: in progress

#755 Add can_create_groups permission
  docs/course_permissions.csv
  migrations/versions/f2563a55410c7c6d3d38_.py
  psef/errors.py
  psef/permissions.py
  psef/v1/group_sets.py
  psef_test/test_groups.py
  seed_data/course_roles.json
  seed_data/permissions.json
  src/components/GroupsManagement.vue
Labels: in progress

#754 Hide submit button when there are no group sets
  src/components/AssignmentGroup.vue
  src/components/DivideSubmissions.vue
  src/pages/ManageAssignment.vue
  src/style.less
Labels: in progress

#761 Fix submit button for user info
  src/components/UserInfo.vue
Labels: in progress

#763 Various front-end UI fixes
  src/components/PlagiarismDetail.vue
  src/components/Sidebar/index.vue
  src/components/index.js
  src/pages/Submission.vue
  src/utils/FilterSubmissionsManager.js
Labels: in progress

#764 Fix grade submission when rubric was both edited and overridden
  src/components/GradeViewer.vue
Labels: in progress

#765 Fix submitting grade when assignment has no rubric
  src/components/GradeViewer.vue
Labels: in progress

#766 Show message when uploaded file is empty
  src/components/InnerCodeViewer.vue
Labels: in progress

#775 Update changelog
  docs/about/changelog.rst
Labels: in progress

#787 Add a release notifier on the home grid
  build/userConfig.js
  src/components/FooterBar.vue
  src/components/HomeGrid.vue
  src/components/Sidebar/index.vue
Labels: in progress

#788 Make it possible to import rubrics from other assignments
  psef/models/rubric.py
  psef/v1/assignments.py
  psef_test/helpers.py
  psef_test/test_assignments.py
  src/components/PlagiarismRunner.vue
  src/components/RubricEditor.vue
  src/pages/ManageAssignment.vue
Labels: in progress

#793 Reserve some extra special filenames
  psef/files.py
Labels: in progress

#792 Clearer plagiarism similarity placeholder
  psef/plagiarism.py
  psef/plagiarism_providers/jplag.py
  psef_test/test_plagiarism.py
Labels: in progress

#794 Make it possible to connect assignment divisions
  Makefile
  docs/user/management.rst
  migrations/versions/193f394089dd_.py
  psef/exceptions.py
  psef/models/assignment.py
  psef/models/work.py
  psef/v1/assignments.py
  psef_test/helpers.py
  psef_test/test_assignments.py
  psef_test/test_course.py
  src/components/DivideSubmissions.vue
  src/components/FinishedGraderToggles.vue
  src/pages/ManageAssignment.vue
  src/style.less
Labels: in progress

#800 Add link to about us page in the footer
  src/components/FooterBar.vue
Labels: frontend, in progress, little work

#799 Fix bug when reloading assignments on submission page
  src/pages/Submission.vue
Labels: in progress

#798 Make it impossible to list all users on the system by searching
  psef/helpers/__init__.py
  psef_test/test_users.py
  src/components/UserSelector.vue
Labels: in progress

#801 Add warning on permission management page
  src/components/PermissionsManager.vue
Labels: frontend, in progress, little work

#790 Rewrite SubmitButton component
  psef/v1/login.py
  src/components/AssignmentGroup.vue
  src/components/CGIgnoreFile.vue
  src/components/DivideSubmissions.vue
  src/components/FeedbackArea.vue
  src/components/FileUploader.vue
  src/components/ForgotPassword.vue
  src/components/GeneralFeedbackArea.vue
  src/components/GradeReminder.vue
  src/components/GradeViewer.vue
  src/components/GroupManagement.vue
  src/components/GroupSetManager.vue
  src/components/GroupsManagement.vue
  src/components/Linter.vue
  src/components/Login.vue
  src/components/MaximumGrade.vue
  src/components/Notifications.vue
  src/components/PasswordSuggestions.vue
  src/components/PermissionsManager.vue
  src/components/PlagiarismDetail.vue
  src/components/PlagiarismRunner.vue
  src/components/Register.vue
  src/components/RubricEditor.vue
  src/components/Sidebar/AssignmentList.vue
  src/components/Sidebar/CourseList.vue
  src/components/SnippetManager.vue
  src/components/SubmissionList.vue
  src/components/SubmissionUploader.vue
  src/components/SubmitButton.vue
  src/components/SubmitInput.vue
  src/components/UserInfo.vue
  src/components/UsersManager.vue
  src/components/index.js
  src/constants.js
  src/pages/Groups.vue
  src/pages/ManageAssignment.vue
  src/pages/ResetPassword.vue
  src/pages/Submission.vue
  src/store/modules/user.js
  src/style.less
  test/unit/specs/FeedbackArea.spec.js
  test/unit/specs/IPythonViewer.spec.js
  test/unit/specs/MaximumGrade.spec.js
  test/unit/specs/PlagiarismRunner.spec.js
  test/unit/specs/SnippetManager.spec.js
  test/unit/specs/Submission.spec.js
  test/unit/specs/SubmitButton.spec.js
Labels: in progress

#802 Make it possible to download the plagiarism log
  src/components/PlagiarismOverview.vue
Labels: frontend, in progress

#805 Merge the loaders of the plagiarism runner
  src/components/PlagiarismRunner.vue
Labels: in progress

#807 Make sure 500 never occur because of `__maybe_add_warning` function
  psef/helpers/__init__.py
Labels: in progress

#804 Make it possible to resize the filetree
  index.html
  npm-shrinkwrap.json
  package.json
  src/App.vue
  src/components/FileTree.vue
  src/components/GradeViewer.vue
  src/components/IPythonViewer.vue
  src/components/InnerMarkdownViewer.vue
  src/pages/Submission.vue
  src/style.less
Labels: in progress

#806 Use SubmitButton in AssignmentState
  src/components/AssignmentState.vue
  src/components/SubmitButton.vue
Labels: in progress

#812 Make it possible to search the homegrid
  src/components/CategorySelector.vue
  src/components/HomeGrid.vue
  src/components/LocalHeader.vue
  src/components/PlagiarismOverview.vue
Labels: in progress

#809 Prevent error in console when not logged in on page load
  psef/helpers/__init__.py
  psef/models/permission.py
  psef/models/user.py
  psef/v1/login.py
  psef/v1/permissions.py
  psef_test/test_login.py
  psef_test/test_permissions.py
  src/App.vue
  src/components/HomeGrid.vue
  src/components/Login.vue
  src/components/PermissionsManager.vue
  src/components/Sidebar/index.vue
  src/constants.js
  src/main.js
  src/pages/LTILaunch.vue
  src/permissions.js
  src/router/index.js
  src/store/modules/courses.js
  src/store/modules/user.js
  src/style.less
Labels: in progress

#811 Enable use of multiple LTI providers
  config.ini.example
  psef/helpers/register.py
  psef/lti.py
  psef/models/lti_provider.py
  psef/v1/lti.py
  psef_test/conftest.py
  psef_test/test_lti.py
Labels: in progress

#813 Make it possible to show progress for plagiarism providers
  migrations/versions/1edd7a1f8efc_.py
  psef/helpers/__init__.py
  psef/models/plagiarism.py
  psef/plagiarism.py
  psef/plagiarism_providers/jplag.py
  psef/tasks.py
  psef/v1/plagiarism.py
  psef_test/test_plagiarism.py
  src/components/PlagiarismRunner.vue
Labels: in progress
